import { useEffect, useRef } from "react";
import { ExpenseEntry, MutualFund, PortfolioData, RecurringDeposit, RecurringRule } from "../types";
import { processAutoGeneratedEntries } from "../lib/utils";

// Cheap signature covering only the fields that drive auto-generation:
//   - SIP sources (MF sipDetails fields + fund identity / createdAt)
//   - RD sources (all fields used by processRDDeductions)
//   - Recurring rules (all scheduling fields + lastProcessedMonth)
//   - Sorted IDs of existing auto-generated expenses (detects deletions)
//
// Intentionally excludes totalSIPInvested (computed-only, never read by UI),
// currentValue, lumpsumEntries, stockPortfolios, etc.
function autoSchedulerSig(
  expenses: ExpenseEntry[],
  mutualFunds: MutualFund[],
  rd: RecurringDeposit[],
  recurringRules: RecurringRule[],
): string {
  const sipSig = mutualFunds
    .filter((f) => !!f.sipDetails)
    .map((f) => {
      const s = f.sipDetails!;
      return [
        f.id, f.fundName, f.createdAt ?? "",
        s.startDate, s.status, s.monthlyAmount,
        s.fromAccountId ?? "", s.fromAccountName ?? "",
        s.paymentMethod ?? "", s.stoppedDate ?? "",
      ].join("|");
    })
    .join(";");

  const rdSig = rd
    .map((r) => [
      r.id, r.bankName, r.startDate, r.maturityDate, r.monthlyDeposit,
      r.fromAccountId ?? "", r.fromAccountName ?? "",
      r.paymentMethod ?? "", r.createdAt ?? "",
    ].join("|"))
    .join(";");

  const ruleSig = recurringRules
    .map((r) => [
      r.id, r.isActive ? 1 : 0, r.startDate, r.endDate ?? "",
      r.frequency, r.dayOfMonth ?? "", r.dayOfWeek ?? "", r.monthOfYear ?? "",
      r.amount, r.category, r.paymentMethod,
      r.fromAccountId ?? "", r.fromAccountName ?? "",
      r.lastProcessedMonth ?? "",
    ].join("|"))
    .join(";");

  // Sorted auto-generated expense IDs detect both additions and deletions.
  const autoIdsSig = expenses
    .filter((e) => e.isAutoGenerated)
    .map((e) => e.id)
    .sort()
    .join(",");

  return `${sipSig}~${rdSig}~${ruleSig}~${autoIdsSig}`;
}

export function useAutoScheduler(
  data: PortfolioData,
  updateData: (data: Partial<PortfolioData>) => void,
) {
  const lastSigRef = useRef("");

  useEffect(() => {
    const sig = autoSchedulerSig(
      data.expenses,
      data.investments.mutualFunds,
      data.investments.rd,
      data.recurringRules,
    );

    // Skip the expensive processAutoGeneratedEntries call entirely when
    // nothing auto-generation-relevant has changed since the last run.
    if (sig === lastSigRef.current) return;
    lastSigRef.current = sig;

    const scheduled = processAutoGeneratedEntries(data);

    // Compare the output signature to the input signature instead of
    // JSON-stringifying the full expenses/investments/recurringRules arrays.
    const outSig = autoSchedulerSig(
      scheduled.expenses,
      scheduled.investments.mutualFunds,
      data.investments.rd,          // RDs are unchanged by processAutoGeneratedEntries
      scheduled.recurringRules,
    );

    if (outSig !== sig) {
      updateData(scheduled);
    }
  }, [data, updateData]);
}
